/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2018-11-18 05:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Date;
import java.text.*;
import java.io.*;
import javax.servlet.*;

public final class roomupdate1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"calendar/zapatec/zpcal/themes/wood.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"calendar/zapatec/zpcal/utils/zapatec.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"calendar/zapatec/zpcal/src/calendar.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"calendar/zapatec/zpcal/lang/calendar-en.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("background-image:url('hotel_room_bed_furniture_luxury_70053_1680x1050.jpg');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a:link{\r\n");
      out.write("color:blue;\r\n");
      out.write("font-size:20pt;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a:visited{\r\n");
      out.write("font-size:20pt;\r\n");
      out.write("color:Navy;\r\n");
      out.write("background-color:transparent;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("color:red;\r\n");
      out.write("background-color:transparent;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("a:active{\r\n");
      out.write("color:blue;\r\n");
      out.write("background-color:transparent;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#t2{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("width:100%;\r\n");
      out.write("height:300%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("margin:top;\r\n");
      out.write("\tcolor:tomato;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-family: 'Oleo Script', cursive;;\r\n");
      out.write("\tfont-size:60pt;\r\n");
      out.write("\ttext-shadow:5px 5px 5px green;}\r\n");
      out.write("\t\r\n");
      out.write("h3{\r\n");
      out.write("font-size:24pt;\r\n");
      out.write("color:red;\r\n");
      out.write("align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".th{\r\n");
      out.write("background-color:DarkSalmon;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("font-size:15pt;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".td{\r\n");
      out.write("font-size:13pt;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("color:Tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("b{font-size:20pt;\r\n");
      out.write("color:red;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<h1 align=\"center\" >Online Hotel Booking System</h1>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td class=\"link\">\r\n");
      out.write("\t<a href=\"RoomBooking.jsp\">View Rooms</a><br><br>\r\n");
      out.write("\t<a href=\"available.jsp\">View Available Rooms</a><br><br>\r\n");
      out.write("\t<a href=\"bookingForm.jsp\">Check-in Rooms</a><br><br>\r\n");
      out.write("\t<a href=\"cancel1.jsp\">Cancel Booking</a><br><br>\r\n");
      out.write("\t<a href=\"review.jsp\">Review  Booking</a><br><br>\r\n");
      out.write("\t<a href=\"logout.jsp\">Logout</a><br><br>\r\n");
      out.write("\t<a href=\"home.html\">Home</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"right\">\r\n");
      out.write("\t\r\n");

String rno=request.getParameter("rno");
String sdate=request.getParameter("sdate");
String edate=request.getParameter("edate");


String name=(String)session.getAttribute("name");
String pass=(String)session.getAttribute("pass");
System.out.println(name);
System.out.println(pass);
session.setAttribute("name",name);
session.setAttribute("pass",pass);
System.out.println("Start date from Room Booking ... "+sdate);
System.out.println("End date from Room Booking ... "+edate);
String sql3;

Connection con;
Statement stmt;
ResultSet rs;
String sql;
String sql1;
String available;
String statusupdate;
int rid=0;
int gid=0;
boolean result=true;boolean r=true;
/* String end_date="";
String start_date=""; */
Date ed;Date sd;Date sed;Date ssd;Date cur;
String dd;
Date stdate;
Date eddate;
	Class.forName("com.mysql.jdbc.Driver");
	
		con=DriverManager.getConnection("jdbc:mysql://localhost:3306/group8","root","mic1");
		System.out.println("Connection Successful!");
		
		Date d=new Date();
		DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
		String curdate=dateFormat.format(d);
		System.out.println(curdate);
		cur=new SimpleDateFormat("yyyy-MM-dd").parse(curdate);
		
		String delete="select end_date from booking";
		Statement edelete=con.createStatement();
		rs=edelete.executeQuery(delete);
		while(rs.next()){
				ed=rs.getDate("end_date");
				System.out.println(ed);
				
				if(cur.compareTo(ed)>0){
				String rdelete="delete from booking where end_date='"+ed+"'";
				Statement sdelete=con.createStatement();
				sdelete.executeUpdate(rdelete);
				

				String supdate="update room set status=1 where rid like(select rid from booking where end_date='"+ed+"')";
				Statement st=con.createStatement();
				st.executeUpdate(supdate);
				}
		}//while
			
		 stdate=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
		boolean tr=true;
		if(cur.compareTo(stdate)>0){
			tr=false;
		}
if(tr){//cur compare stdate	
		String rn="select rno from room where rno='"+rno+"' and status=0";
		Statement stm=con.createStatement();
		rs=stm.executeQuery(rn);
		while(rs.next()){
			result=false;
		}
		
if(result){
			String yn="select rid from booking where rid like (select rid from room where rno='"+rno+"')";
			stmt=con.createStatement();
			rs=stmt.executeQuery(yn);
			boolean res=false;
			while(rs.next()){
				res=true;
			}
			if(res){

				dd="select booking.start_date,booking.end_date from booking,room where room.rid=booking.rid and room.rno='"+rno+"'";
				stmt=con.createStatement();
				rs=stmt.executeQuery(dd);
				
				while(rs.next()){
					ed=rs.getDate("end_date");
					sd=rs.getDate("start_date");
				
					/* isd=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
					ed=new SimpleDateFormat("yyyy-MM-dd").parse(end_date);
					sd=new SimpleDateFormat("yyyy-MM-dd").parse(start_date);
					ied=new SimpleDateFormat("yyyy-MM-dd").parse(edate); */
					 stdate=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
				     eddate=new SimpleDateFormat("yyyy-MM-dd").parse(edate);
					if(stdate.compareTo(ed)>0|| sd.compareTo(eddate)>0){
						r=true;
					   }//date compare if
					   else{//date compare else 
						   r=false;
					   		break;
					   }
				}//while closint tag
					   	  if(r){//r true
					   		  /* if(cur.compareTo(stdate)==0){ */
					   		 	statusupdate="update room set status='0' where rno='"+rno+"'";
								stmt=con.createStatement();
								stmt.executeUpdate(statusupdate);
					   		  
								sql="select gid from guest where name='"+name+"' and password='"+pass+"'";
								stmt=con.createStatement();
								rs=stmt.executeQuery(sql);
								
								while(rs.next()){
								//String g=rs.getString("gid");
								gid=rs.getInt("gid");
								System.out.println("Guest Id by login user name  !!!! "+gid);
								}
								
								sql1="select rid from room where rno='"+rno+"'";
								stmt=con.createStatement();
								rs=stmt.executeQuery(sql1);
								while(rs.next()){
								//String r=rs.getString("rid");
								rid=rs.getInt("rid");
								System.out.println("Room Id by Room No ... "+rid);
								}
								
								sql3="insert into booking values(null,?,?,?,?)";
								PreparedStatement ps=con.prepareStatement(sql3);
								ps.setInt(1,gid);
								ps.setInt(2,rid);
								//convert util date to sqldate
							
								ps.setDate(3,java.sql.Date.valueOf(sdate));
								ps.setDate(4,java.sql.Date.valueOf(edate));
								ps.executeUpdate();
								
								/* out.println("<h1>Booking Successful!If you would like to check-in again.</h1>");
								RequestDispatcher rd=request.getRequestDispatcher("RoomBooking.jsp");
								rd.forward(request, response); */
								String str="<b>Booking Successful!If you would like to check-in again.</b>";
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("bookingForm.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(str ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

				   	  }else{
					   dd="select booking.start_date,booking.end_date from booking,room where room.rid=booking.rid and room.rno='"+rno+"'";
						stmt=con.createStatement();
						rs=stmt.executeQuery(dd);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 
						while(rs.next()){
							ed=rs.getDate("end_date");
							sd=rs.getDate("start_date");
						
						out.print("<br><b>You can't check-in this room between "+sd+"and"+ed+".</b>");
						
						}
						out.print("<b>You can check-in the following available rooms!</b>");
						stdate=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
					    eddate=new SimpleDateFormat("yyyy-MM-dd").parse(edate);
					    System.out.println("user start date"+stdate);
						System.out.println("user end date"+eddate);
						available="select rid,start_date,end_date from booking";
						stmt=con.createStatement();
						rs=stmt.executeQuery(available);
						while(rs.next()){
							rid=rs.getInt("rid");
							ed=rs.getDate("end_date");
							sd=rs.getDate("start_date");
							System.out.println("table end date"+ed);
							System.out.println("table start date"+sd);
							
							if(stdate.compareTo(ed)>0 || eddate.compareTo(sd)<0){
																
							
							 	statusupdate="update room set status=1 where rid="+rid;
								stmt=con.createStatement();
								stmt.executeUpdate(statusupdate);
								System.out.println("update successful");
							}
						}
						
						available="select room.rno,roomtype.typename,roomtype.price from room,roomtype where room.rtypeid=roomtype.rtypeid and room.status=1";
						stmt=con.createStatement();
						rs=stmt.executeQuery(available);
						
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\" width=\"500\" height=\"100\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th\">Room_No</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th\">Room_Type</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th\">Price</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
 
						while(rs.next()){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getString("rno") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getString("typename") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getInt("price") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						} 
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <form action=\"roomupdate1.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t<tr><td>Booking Room No</td><td><input type=\"text\" name=\"rno\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td><label for=\"date\">Start Date:</label></td><td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"sdate\" maxlength=\"400\"\tsize=\"15\"   \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-color: rgb(255, 255, 160);\" readonly=\"readonly\" id=\"calendar\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"trigger\">...</button> \r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//         \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tZapatec.Calendar.setup({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfirstDay : 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telectric : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tinputField : \"calendar\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbutton : \"trigger\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tifFormat : \"%Y-%m-%d\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdaFormat : \"%Y-%m-%d\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td><label for=\"edate\">End Date:</label></td><td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"edate\" maxlength=\"400\"\tsize=\"15\"   \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-color: rgb(255, 255, 160);\" readonly=\"readonly\" id=\"calendar1\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"trigger1\">...</button> \r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//         \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tZapatec.Calendar.setup({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfirstDay : 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telectric : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tinputField : \"calendar1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbutton : \"trigger1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tifFormat : \"%Y-%m-%d\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdaFormat : \"%Y-%m-%d\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td><input type=\"submit\" value=\"Confirm\" name=\"confirm\" class=\"btn\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"reset\" value=\"Cancel\" name=\"cancel\" class=\"btn\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t\t");

				   }//r else closing tag
				
		}//res if
		
		else{//res else
			
			statusupdate="update room set status='0' where rno='"+rno+"'";
			stmt=con.createStatement();
			stmt.executeUpdate(statusupdate);
			 
			sql="select gid from guest where name='"+name+"' and password='"+pass+"'";
			stmt=con.createStatement();
			rs=stmt.executeQuery(sql);
		
			while(rs.next()){
			//String g=rs.getString("gid");
			gid=rs.getInt("gid");
			System.out.println("Guest Id by login user name  !!!! "+gid);
			}
		
			sql1="select rid from room where rno='"+rno+"'";
			stmt=con.createStatement();
			rs=stmt.executeQuery(sql1);
			while(rs.next()){
			//String r=rs.getString("rid");
			rid=rs.getInt("rid");
			System.out.println("Room Id by Room No ... "+rid+"");
			}
		
			sql3="insert into booking values(null,?,?,?,?)";
			PreparedStatement ps=con.prepareStatement(sql3);
			ps.setInt(1,gid);
			ps.setInt(2,rid);
			//convert util date to sqldate
			ps.setDate(3,java.sql.Date.valueOf(sdate));
			ps.setDate(4,java.sql.Date.valueOf(edate));
			//java.sql.Date d=convertUtilToSql(stdate);
			
			ps.executeUpdate();
			
			/* out.println("<h1>Booking Successful!If you would like to check-in again.</h1>");
			RequestDispatcher rd=request.getRequestDispatcher("RoomBooking.jsp");
			rd.forward(request, response); */
			String str="Booking Successful!If you would like to check-in again.";
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("bookingForm.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(str ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\t\t\t");

			}//res else closing tag
}//result if
else{
				
				dd="select booking.start_date,booking.end_date from booking,room where room.rid=booking.rid and room.rno='"+rno+"'";
				stmt=con.createStatement();
				rs=stmt.executeQuery(dd);
				String st="";
				sdate=request.getParameter("sdate");
				edate=request.getParameter("edate");
				while(rs.next()){
						ed=rs.getDate("end_date");
						sd=rs.getDate("start_date");
						 stdate=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
					     eddate=new SimpleDateFormat("yyyy-MM-dd").parse(edate);	
					if(stdate.compareTo(ed)>0 || sd.compareTo(eddate)>0){
							r=true;
					}//date compare
					else{//date compare else
						
						r=false;
						break;
					}// compare else closing tag
				}//while closing tag
				if(r){
					
				 	statusupdate="update room set status='0' where rno='"+rno+"'";
					stmt=con.createStatement();
					stmt.executeUpdate(statusupdate);
					
					sql="select gid from guest where name='"+name+"' and password='"+pass+"'";
					stmt=con.createStatement();
					rs=stmt.executeQuery(sql);
					
					while(rs.next()){
					//String g=rs.getString("gid");
					gid=rs.getInt("gid");
					System.out.println("Guest Id by login user name  !!!! "+gid);
					}
					
					sql1="select rid from room where rno='"+rno+"'";
					stmt=con.createStatement();
					rs=stmt.executeQuery(sql1);
					while(rs.next()){
					//String r=rs.getString("rid");
					rid=rs.getInt("rid");
					System.out.println("Room Id by Room No ... "+rid);
					}
					
					sql3="insert into booking values(null,?,?,?,?)";
					PreparedStatement ps=con.prepareStatement(sql3);
					ps.setInt(1,gid);
					ps.setInt(2,rid);
					ps.setDate(3,java.sql.Date.valueOf(sdate));
					ps.setDate(4,java.sql.Date.valueOf(edate));
					ps.executeUpdate();
					
					
					String str="Booking Successful!If you would like to check-in again.";
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("bookingForm.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(str ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\t\t");

			}//r if
			else{//r else

				dd="select booking.start_date,booking.end_date from booking,room where room.rid=booking.rid and room.rno='"+rno+"'";
				stmt=con.createStatement();
				rs=stmt.executeQuery(dd);
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

						
				while(rs.next()){
						ed=rs.getDate("end_date");
						sd=rs.getDate("start_date");
						out.print("<br><b>You can't check-in between "+sd+"and"+ed+"</b>");
				}
				out.print("<br><b>You can check-in the following rooms!</b>");
				
				stdate=new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
			    eddate=new SimpleDateFormat("yyyy-MM-dd").parse(edate);
			    System.out.println("user start date"+stdate);
				System.out.println("user end date"+eddate);
				
				available="select rid,start_date,end_date from booking";
				stmt=con.createStatement();
				rs=stmt.executeQuery(available);
				while(rs.next()){
					rid=rs.getInt("rid");
					ed=rs.getDate("end_date");
					sd=rs.getDate("start_date");
					//System.out.println("table end date"+ed);
					//System.out.println("table start date"+sd);
					
					if(stdate.compareTo(ed)>0 || eddate.compareTo(sd)<0){
					 	statusupdate="update room set status=1 where rid="+rid;
						stmt=con.createStatement();
						stmt.executeUpdate(statusupdate);
						System.out.println("update successful");
					}
				}
				
				
				available="select room.rno,roomtype.typename,roomtype.price from room,roomtype where room.rtypeid=roomtype.rtypeid and room.status=1";
				stmt=con.createStatement();
				rs=stmt.executeQuery(available);
				
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<table border=\"1\" width=\"500\" height=\"100\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"th\">Room_No</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"th\">Room_Type</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"th\">Price</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 
					while(rs.next()){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getString("rno") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getString("typename") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td\">");
      out.print(rs.getInt("price") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					} 
				
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t");
}//r else
	}//result else
}//cur compare stdate
else{//cur compare else
	String str="You can't check-in cause of your date out.<br> Please try again!";
	


      if (true) {
        _jspx_page_context.forward("bookingForm.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(str ), request.getCharacterEncoding()));
        return;
      }
      out.write('\r');
      out.write('\n');
} 
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
