/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2019-08-21 13:31:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class adminTrue1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"design.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#but{\r\n");
      out.write("height:35px;\r\n");
      out.write("width:80px;color:black;\r\n");
      out.write("font-size:16px;}\r\n");
      out.write("#room{\r\n");
      out.write("width:145px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write("#sub{\r\n");
      out.write("width:50px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write(".th{\r\n");
      out.write("background-color:#8E35EF;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("font-size:15pt;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".td{\r\n");
      out.write("font-size:13pt;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("margin:top;\r\n");
      out.write("\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size:50pt;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("div{\r\n");
      out.write("padding-bottom:50px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".lab1{\r\n");
      out.write("width:145px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write("#sub{\r\n");
      out.write("width:50px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write("#but{\r\n");
      out.write("height:35px;\r\n");
      out.write("width:130px;color:black;\r\n");
      out.write("font-size:16px;}\r\n");
      out.write(".dropdown{\r\n");
      out.write("padding-bottom:100px;\r\n");
      out.write("}\r\n");
      out.write("div{\r\n");
      out.write("padding-top:100px;}\r\n");
      out.write(".info{\r\n");
      out.write("padding-bottom:300px;\r\n");
      out.write("font-size:25pt;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


String add=request.getParameter("add");
String ok=request.getParameter("ok");
String room=request.getParameter("room");
String change=request.getParameter("change");
String st=request.getParameter("st");
//String st=(String)session.getAttribute("st");
if(add!=null)
{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"add.jsp\">\r\n");
      out.write("\t<table border=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>Room No:</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"rno\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>Room Type:</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"room\" id=\"room\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<option disabled>Room Type</option>\r\n");
      out.write("\t\t<option value=\"single\">Single Room</option>\r\n");
      out.write("\t\t<option value=\"double\">Double Room</option>\r\n");
      out.write("\t\t<option value=\"family\">Family Room</option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><a href=\"adminTrue.jsp\">Back</a></td>\r\n");
      out.write("\t\t<td><input type=\"submit\" name=\"add\" value=\"Add\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");

}
else if(ok!=null){
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("Adminviewroom.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("room", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(room ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

}
else if(change!=null){
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("ChangePrice.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("room", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(room ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

}
else{

      out.write("\r\n");
      out.write("<table border=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<h1 align=\"center\" >Online Hotel Booking System</h1>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<td align=\"left\" class=\"dropdown\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<form action=\"adminTrue.jsp\">\r\n");
      out.write("\t<select name=\"room\" id=\"room\">\r\n");
      out.write("\t<option disabled>Room Type</option>\r\n");
      out.write("\t<option value=\"single\">Single Room</option>\r\n");
      out.write("\t<option value=\"double\">Double Room</option>\r\n");
      out.write("\t<option value=\"family\">Family Room</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<input type=\"submit\" value=\"OK\" id=\"sub\" width=\"100px\" name=\"ok\">\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<input type=\"submit\" value=\"Add New Room\" width=\"100px\" id=\"but\" name=\"add\">\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<input type=\"submit\" value=\"Change Price\" width=\"100px\" id=\"but\" name=\"change\" >\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td id=\"const\">\r\n");
      out.write("\t");

	if(st!=null){
		
      out.write("\r\n");
      out.write("\t\t<font class=\"info\"><i>");
      out.print(st );
      out.write("</i></font>\r\n");
      out.write("\t\t");

	}
	
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
 
	}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
