/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2019-08-21 14:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Admindelete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"design.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("h1{\r\n");
      out.write("margin:top;\r\n");
      out.write("\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size:50pt;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("div{\r\n");
      out.write("padding-bottom:400px;}\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("padding-bottom:400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<h1 align=\"center\" >Online Hotel Booking System</h1>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t<form action=\"Adminviewroom.jsp\">\r\n");
      out.write("\t\t\t\t<select name=\"room\" id=\"room\">\r\n");
      out.write("\t\t\t\t<option disabled>Room Type</option>\r\n");
      out.write("\t\t\t\t<option value=\"single\">Single Room</option>\r\n");
      out.write("\t\t\t\t<option value=\"double\">Double Room</option>\r\n");
      out.write("\t\t\t\t<option value=\"family\">Family Room</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"OK\" id=\"sub\" width=\"100px\">\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Add\" width=\"100px\" id=\"but\">\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Change Price\" width=\"100px\" id=\"but\" name=\"change\" >\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"700px\" height=\"500px\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t");

					
					boolean cond=false;
					//String rid=null;
					//rid=(String)session.getAttribute("rid");
				
					//if(rid==null){
						String rid=request.getParameter("rid");
						int ri=Integer.parseInt(rid);
						Connection con;
						Statement stmt;
						ResultSet rs;
						String sql;
						
						Class.forName("com.mysql.jdbc.Driver");
						
						con=DriverManager.getConnection("jdbc:mysql://localhost:3306/group8","root","root");
						System.out.println("Connection Successful!");
						System.out.println("rid from table"+ri);
						
						sql="select * from booking where rid="+ri;
						stmt=con.createStatement();
						rs=stmt.executeQuery(sql);
						boolean book=false;
						while(rs.next()){
							book=true;
						}
						String st="";
						String room="";
						if(book){
						st="You can't delete this booking room!";
						//out.println("<h2>You can't delete this booking room!</h2>");
						cond=true;	
						}
						else{
							
						sql="delete from room where rid="+ri;
						stmt=con.createStatement();
						stmt.executeUpdate(sql);
						st="Delete Room is successful!";
						//out.println("<h2>Delete Room is successful!'</h2>");
						sql="select typename from roomtype where rtypeid like(select rtypeid from room where rid="+ri+")";
						stmt=con.createStatement();
						rs=stmt.executeQuery(sql);
						
						while(rs.next()){
							room=rs.getString("typename");
						}
						System.out.println("room type :"+room);
						}
						//System.out.println(st);
						//session.setAttribute("st", st);
						//response.sendRedirect("./Adminviewroom.jsp");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("adminTrue1.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("st", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(st ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("room", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(room ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
