/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2019-08-21 03:24:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class ChangePriceProcessing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"design.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("th{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input.txt{\r\n");
      out.write("height:20px;\r\n");
      out.write("width:160px;}\r\n");
      out.write("#but{\r\n");
      out.write("height:30px;\r\n");
      out.write("width:130px;color:black;\r\n");
      out.write("font-size:16px;}\r\n");
      out.write("#bu{\r\n");
      out.write("height:35px;\r\n");
      out.write("width:80px;color:black;\r\n");
      out.write("font-size:16px;}\r\n");
      out.write(".info{\r\n");
      out.write("font-size:20pt;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("div{\r\n");
      out.write("padding-bottom:400px;}\r\n");
      out.write("#room{\r\n");
      out.write("width:160px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write("#sub{\r\n");
      out.write("width:50px;\r\n");
      out.write("height:35px;\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("padding-bottom:350px;}\r\n");
      out.write(".info{\r\n");
      out.write("padding-bottom:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String add=request.getParameter("add");
String ok=request.getParameter("ok");
String change=request.getParameter("change");
String room=request.getParameter("room");
String p=request.getParameter("price");
int price=Integer.parseInt(p);
if(add!=null)
{
	Connection con;
	Statement stmt;
	ResultSet rs;
	String sql;

	Class.forName("com.mysql.jdbc.Driver");

	con=DriverManager.getConnection("jdbc:mysql://localhost:3306/group8","root","root");
	System.out.println("Connection Successful!");

	sql="select price from roomtype where typename='"+room+"'";
	stmt=con.createStatement();
	rs=stmt.executeQuery(sql);
	int pri=0;
	while(rs.next()){
		pri=rs.getInt("price");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">Online Hotel Booking System</h1>\r\n");
      out.write("<form action=\"add.jsp\">\r\n");
      out.write("\t<table border=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th><h3>Room No:</h3></th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"rno\" class=\"txt\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th><h3>Room Type:</h3></th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"room\" id=\"room\">\r\n");
      out.write("\t\t<option disabled>Room Type</option>\r\n");
      out.write("\t\t<option value=\"single\">Single Room</option>\r\n");
      out.write("\t\t<option value=\"double\">Double Room</option>\r\n");
      out.write("\t\t<option value=\"family\">Family Room</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th><h3>Price:</h3></th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"price\" class=\"txt\"  value=\"");
      out.print(pri);
      out.write("\" disabled></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><a href=\"adminTrue.jsp\">Back</a></td>\r\n");
      out.write("\t\t<td><input type=\"submit\" name=\"add\" value=\"Add\" id=\"bu\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");

}
else if(ok!=null){
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("Adminviewroom.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("room", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(room ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

}
else if(change!=null){
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("ChangePrice.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("room", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(room ), request.getCharacterEncoding()));
        return;
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

}
else{
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<h1 align=\"center\" >Online Hotel Booking System</h1>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td align=\"left\" class=\"dropdown\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<form action=\"adminTrue.jsp\">\r\n");
      out.write("\t\t<select name=\"room\" id=\"room\">\r\n");
      out.write("\t\t<option disabled>Room Type</option>\r\n");
      out.write("\t\t<option value=\"single\">Single Room</option>\r\n");
      out.write("\t\t<option value=\"double\">Double Room</option>\r\n");
      out.write("\t\t<option value=\"family\">Family Room</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"OK\" id=\"sub\" width=\"100px\" name=\"ok\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Add New Room\" width=\"100px\" id=\"but\" name=\"add\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Change Price\" width=\"100px\" id=\"but\" name=\"change\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td width=\"700px\" height=\"500px\" align=\"center\" class='info' >\r\n");
      out.write("\t\t\t");

			Connection con;
			Statement stmt;
			ResultSet rs;
			String sql;
			
			Class.forName("com.mysql.jdbc.Driver");
			
			con=DriverManager.getConnection("jdbc:mysql://localhost:3306/group8","root","root");
			System.out.println("Connection Successful!");
			
			String sql1="update roomtype set price="+price+" where typename='"+room+"'";
			stmt=con.createStatement();
			stmt.executeUpdate(sql1);
			
			
      out.write("\r\n");
      out.write("\t\t\t<h2><i>Change Price Successful!</i></h2>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
